### ISSUE TITLE
How to configure `policy.yml` for a run?

### ISSUE THREAD

**Issue by rajbos** [ossf/scorecard-action#1098]
How can we configure a `policy.yml` file for a run? 
I see there is a [template file](https://github.com/ossf/scorecard-action/blob/main/policies/template.yml) available, but I do not see it being used. Seems like the container would use it, but we ware not passing it into the container params (I think).

I am trying to run the action internally on GHES, and our runners do not have internet access, so downloading the extra clients is failing:

``` yaml
Error: GetClients: getting OSS-Fuzz repo client: error during InitRepo: repo unreachable: Get "https://api.github.com/repos/google/oss-fuzz": internal error: innerTransport.RoundTrip: internal error: innerTransport.RoundTrip: error in HTTP: dial tcp 140.82.121.6:443: i/o timeout
2023/03/03 15:17:48 error during command execution: GetClients: getting OSS-Fuzz repo client: error during InitRepo: repo unreachable: Get "https://api.github.com/repos/google/oss-fuzz": internal error: innerTransport.RoundTrip: internal error: innerTransport.RoundTrip: error in HTTP: dial tcp w.x.y.z:443: i/o timeout
```

I'd expect that I can configure the policy with fuzzing disabled and get a step further with testing:
``` 
 Fuzzing:
      score: 10
      mode: disabled
```

**Comment by azeemshaikh38** [comment]
@laurentsimon may have more insight on the policy. But without internet access I'd expect Scorecard to fail further too. We rely on making GitHub API calls to get the data we need.

**Comment by rajbos** [comment]
Since it uses the correct environment variable, I was expecting it to make the calls to the correct url 😄 
See here:
https://github.com/ossf/scorecard-action/blob/c59c116cbead5af2de7d75f4d82cf5a2ef5b0304/options/options.go#L69

**Comment by laurentsimon** [comment]
@azeemshaikh38 is correct we need internet access. I'm not that we use `GithubAPIURL` internally. @spencerschrock @azeemshaikh38 do you know?

re: policy. For the policy to work, you need to use `--format sarif` and `--policy path/to/policy.yml`. I think you also need to set `ENABLE_SARIF=1` or it will complain.

**Comment by azeemshaikh38** [comment]
1. https://github.com/ossf/scorecard-action/blob/c59c116cbead5af2de7d75f4d82cf5a2ef5b0304/options/options.go#L69 was meant to help us support GH Enterprise clients. But it hasn't been fully implemented yet, see https://github.com/ossf/scorecard/issues/660. @raghavkaul fyi who is working on getting GHE support end-to-end.
2.  @laurentsimon do we support inputting a policy file to `scorecard-action`? IIUC, @rajbos is trying to use `scorecard-action` on a GHE along with privately hosted Scorecard API.

**Comment by laurentsimon** [comment]
The GHA does not support the policy as input. It's hardcoded for flexibility on our side, but it's not exposed.

**Comment by azeemshaikh38** [comment]
@rajbos looks like we do not currently support the usecase you're trying and I don't see us working on supporting this in the short-term. So closing this issue.

**Comment by rajbos** [comment]
Well, if @raghavkaul is working on an end-to-end setup for GHES instances, I'd like to join that effort. Any links to the work that is being done? Otherwise I'll start one myself by running the container and exposing those inputs.

Would you like/appreciate a PR for that in the future?

**Comment by rajbos** [comment]
I'd love to. I have the injection of the policy file into the container running, but are now waiting on an upstream fix to [ossf/scorecard](https://github.com/ossf/scorecard/issues/2725#issuecomment-1458936845) before I can continue.

**Comment by gabrielkoo** [comment]
For those who would like to customize this, I implemented this workaround:

```yaml
    - name: Filter SARIF to skip irrelevant rules
        env:
          SCORECARD_SKIPPED_RULE_IDS: "${{ vars.SCORECARD_SKIPPED_RULE_IDS }}"
        run: |
          SCORECARD_SKIPPED_RULE_IDS_IN_JSON=$(echo $SCORECARD_SKIPPED_RULE_IDS | jq -cR 'split(",")')
          # Trim the SARIF file to remove skipped rule detections
          cat results.sarif | jq '.runs[].results |= map(select(.ruleId as $id | '$SCORECARD_SKIPPED_RULE_IDS_IN_JSON' | all($id != .)))' > filteredResults.sarif
          # Print the skipped rule detections
          cat results.sarif | jq '.runs[].results | map(select(.ruleId as $id | '$SCORECARD_SKIPPED_RULE_IDS_IN_JSON' | any($id == .))) | select(. | length > 0)'

```

Basically, you have to put a comma separated list into the GitHub Action variable `SCORECARD_SKIPPED_RULE_IDS`.

All checks would still be run, but the `jq` script would filter out the detections that are false positive/irrelevant to your repositories.

Lastly, it still prints out the skipped rule detections in case you want to look at.
