### ISSUE TITLE
Update action hashes in recipe

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard-action#946]
The Scorecard Action recipe relies on a few different GitHub Actions:

```yml
uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5 # tag=v1.0.26
```

These Actions all have newer versions

```yml
uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
uses: github/codeql-action/upload-sarif@904260d7d935dff982205cbdb42025ce30b7a34f # tag=v2.1.24
```

I've already tried the updated `checkout` and `upload-artifact` versions and they work just fine. `checkout` seems to have mostly bumped up a few npm package versions ([changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)). `upload-artifact` added checksums to reduce file corruption issues which apparently happen from time to time ([changelog](https://github.com/actions/upload-artifact/releases/tag/v3.1.0)).

The `codeql-action` has multiple new versions, and has had a major-version increase to v2. [v1 will be deprecated as of December 2022](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/), a warning I've seen displayed... somewhere while setting up the Action. I have not yet checked whether there are any breaking changes between v1 and v2 for `codeql-action/upload-sarif`.
